spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: consul-client-consumer
  cloud:
    consul:
      discovery:
        instance-id: consumer-service-id
        serviceName: consul-client-consumer
#        healthCheckPath: ${management.server.servlet.context-path}/actuator/health
#        healthCheckInterval: 15s
      enabled: true
server:
  port: 8081

